In [1]:
import numpy as np

In [5]:
fpath = r'C:\Users\HP PC\OneDrive\Desktop\tipsf.csv'

In [6]:
np.genfromtxt(fpath, )

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, na

In [7]:
np.genfromtxt(fpath, delimiter = ',',skip_header = True)

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

In [8]:
x = np.genfromtxt(fpath, delimiter = ',',skip_header = True)

In [9]:
x

array([[  0.  ,  16.99,   1.01, ...,   1.  ,   0.  ,   2.  ],
       [  1.  ,  10.34,   1.66, ...,   1.  ,   0.  ,   3.  ],
       [  2.  ,  21.01,   3.5 , ...,   1.  ,   0.  ,   3.  ],
       ...,
       [241.  ,  22.67,   2.  , ...,   0.  ,   0.  ,   2.  ],
       [242.  ,  17.82,   1.75, ...,   0.  ,   0.  ,   2.  ],
       [243.  ,  18.78,   3.  , ...,   2.  ,   0.  ,   2.  ]])

#### 1. what is the total bill value ?

In [14]:
total_bill = np.sum(x[:,1]) 

In [15]:
total_bill

4827.77

#### 2. what is the total tip value ?

In [16]:
total_tip = np.sum(x[:,2]) 

In [17]:
total_tip

731.5799999999999

#### 3. count how many sun,sat,thur,fri are there ?

In [35]:
days = x[:,5] 
unique, counts = np.unique(days, return_counts = True)

In [36]:
for unique, counts in zip(unique, counts):
    print(f"number of {unique}'s : {counts}")

number of 0.0's : 87
number of 1.0's : 76
number of 2.0's : 62
number of 3.0's : 19


#### 4. how many smokers are there ?

In [37]:
smoker = x[:,4] 

In [38]:
np.count_nonzero(smoker == 1)

93

#### 5. what is the average tip given by female and male ?

In [57]:
tip = x[:,2]
sex = x[:,3] 

In [70]:
tip_male = np.mean(tip[sex == 0])
print("the male average tip : ",tip_male)
tip_female = np.mean(tip[sex == 1])
print("the female average tip : ",tip_female)

the male average tip :  2.8334482758620685
the female average tip :  3.0896178343949043


#### 6. how much amount have been spent by female and male ?

In [71]:
amount = x[:,1] 
tip = x[:,2]
sex = x[:,3]

In [115]:
amount_male = np.sum(amount[sex == 0])
tip_male = np.sum(tip[sex == 0])
total_male = amount_male + tip_male
print("the total amount of male : ", total_male)

the total amount of male :  1817.4599999999996


In [117]:
amount_female = np.sum(amount[sex == 1])
tip_female = np.sum(tip[sex == 1])
total_female = amount_female + tip_female
print("the total amount of female : ", total_female)

the total amount of female :  3741.89


#### 7. what is the min, and max tip given ?

In [73]:
tip = x[:,2]

In [78]:
np.min(tip)

1.0

In [75]:
np.max(tip)

10.0

#### 8. how many male and female are going for lunch and dinner ?

In [102]:
time = x[:,6] 
sex = x[:,3]

In [105]:
male_lunch = np.sum((time == 0) & (sex == 0))
male_lunch

52

In [107]:
male_dinner = np.sum((time == 1) & (sex == 0))
male_dinner

35

In [108]:
female_lunch = np.sum((time == 0) & (sex == 1))
female_lunch

124

In [109]:
female_dinner = np.sum((time == 1) & (sex == 1))
female_dinner

33

#### 9. find out the average size ?

In [110]:
size = x[:,7]

In [111]:
np.mean(size)

2.569672131147541

#### 10. how many female smokers and male smokers are there ?

In [112]:
smoker = x[:,4] 
sex = x[:,3]

In [113]:
smoker_male = np.sum(smoker[sex == 0])
print("the total number of male smokers : ", smoker_male)


the total number of male smokers :  33.0


In [114]:
smoker_female = np.sum(smoker[sex == 1])
print("the total number of female smokers : ", smoker_female)

the total number of female smokers :  60.0
