In [1]:
import numpy as np

#### 1.  Write a program to create a 5 dimensional array with all zeros and ones


In [2]:
x = np.zeros((3,3,3,3,3))
print(x)

[[[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]]



 [[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]


  [[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]]]



 [[[[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]]

   [[0. 0. 0.]
    [0. 0. 0.]
    [0. 0. 0.]

In [3]:
y = np.ones((3,3,3,3,3))
print(y)

[[[[[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]]


  [[[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]]


  [[[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]]]



 [[[[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]]


  [[[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]]


  [[[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]]]



 [[[[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]]

   [[1. 1. 1.]
    [1. 1. 1.]
    [1. 1. 1.]

#### 2. Write a program to create an array of 10 zeros,10 ones, and 10 fives in row 1 2 and 3 which create a new array of shape (3,10)


In [4]:
x = np.array([np.zeros(10), np.ones(10), np.full(10,5)])
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.]])

#### 3. Write a program to create a 3x4 matrix filled with values from 10 to 21.


In [5]:
z = np.arange(10,22).reshape(3,4)
z

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

#### 4. Write a  program to create a 10x10 zero matrix with elements on the main diagonal equal to 0,1,2,3,4,5,6,7,8,9,


In [6]:
x = np.zeros((10,10))

In [7]:
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

* np.fill_diagonal = placing specific pieces (values) on those diagonal squares, leaving the rest of the checkerboard unchanged.

In [8]:
np.fill_diagonal(x, np.arange(10))

In [9]:
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 6. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 7. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 8. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


#### 5. Write a program to create a 4x4 array. Create an array from below array by swapping first and last, second and third columns.


In [10]:
original = np.arange(1,17).reshape(4,4)

In [11]:
original

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [12]:
original[:,(0,-1)] = original[:,(-1,0)]

In [13]:
original[:,(1,2)] = original[:,(2,1)]

In [14]:
original

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9],
       [16, 15, 14, 13]])

#### 6.  Write a program to reverse an array (the first element becomes the last).
Given array:
[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 ]


In [15]:
x = np.arange(12,28)

In [16]:
x

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27])

In [17]:
x[::-1] # to print reverse of the above array using the negative slicing.

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

#### 7.   Write a program to access all the elements greater than 30 and less than 80 and multiples of 5 from an array of shape 10,10 .Elements range from 1 to 100

In [18]:
matrix = np.arange(1,101).reshape(10,10)

In [19]:
matrix

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

* np.where = helps you find the indices where a certain condition is true in an array
1. indices = np.where(condition)
where,
* condition is a boolean condition applied to an array.
* np.where returns the indices where the condition is true

In [20]:
multiples = matrix[np.where((matrix > 30) & (matrix < 80) & (matrix % 5 == 0))]

In [21]:
multiples

array([35, 40, 45, 50, 55, 60, 65, 70, 75])

#### 8.   Write a program to create a 2D array with 1 on the border and 0 inside.


In [27]:
x,y = 10,10

In [28]:
z= np.ones((x,y), dtype = int)

In [29]:
z

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [31]:
z[1:-1, 1:-1] = 0 # making middle values as zero's and making rows 
                        # and columns one's

In [32]:
z

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

#### 9.  Write a program to create a checkerboard pattern .Don't use default array function
Checkerboard pattern:                                                   
[[0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]                                                      
 [0 1 0 1 0 1 0 1]                                                      
 [1 0 1 0 1 0 1 0]]


In [33]:
x,y = 10,10

In [34]:
z= np.zeros((x,y), dtype = int)

In [35]:
z

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [36]:
z[1::2, ::2] = 1 # places 1's value in every 2-step

In [37]:
z

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

In [38]:
z[::2, 1::2] = 1 # places 1's value in every 1-step 

In [39]:
z

array([[0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0]])

#### 11.  Write a program to create an array 2d array and then reshape into 1d array

In [43]:
s = np.arange(1,5).reshape(2,2)

In [44]:
s

array([[1, 2],
       [3, 4]])

* np.reshape(-1) =  reshape an array when you want one of the dimensions to be automatically determined based on the length of the array.

In [45]:
a = s.reshape(-1)

In [46]:
a

array([1, 2, 3, 4])