In [1]:
import numpy as np

#### 1. Write a function, foo_1, that takes a NumPy array `arr` and returns the indices of the elements that are closest to a given target. If target is not in the given array, it should return ‘no item found’

In [2]:
def foo(arr, target):
    index = np.where(arr == target)[0]
    if index.size == 0:
        return 'not found'
    return index

input - 1:

In [3]:
arr = np.array([3,8,7,7,7,7,7,8,7,10])

In [4]:
target = 7

In [5]:
foo(arr, target)

array([2, 3, 4, 5, 6, 8], dtype=int64)

input - 2 :

In [6]:
arr = np.array([3,8,7,7,7,7,7,8,7,10])

In [7]:
target = 11

In [8]:
foo(arr, target)

'not found'

### expalintion for above program : 

* step - 1 : import numpy as np imports NumPy to work with arrays
* step - 2: Initialize an empty list index to store the matching indices later
* STEP - 3 : Iterate through arr using enumerate, which gives us the index i and value x
* step - 4 : Compare x to the target. If match, append i to index
* step - 5 : After iteration, if index is empty (length 0), return 'no item found'
* step - 6 : Otherwise, convert index to a NumPy array
* step - 7 : And return the index array

#### 2.  Write a user defined function foo_2 that takes a  2,3 dim NumPy array arr and returns a new n-1 dim array, where each element is replaced by the count of non-zero elements wrt axis

In [76]:
def foo(arr, axis):
    if arr.ndim == 2:
        x=np.where(arr != 0, 1, 0)
        counts=np.sum(x,axis=axis)
        return counts
    elif arr.ndim == 3:
        x=np.where(arr != 0, 1, 0)
        counts=np.sum(x,axis=axis)
        return counts

In [77]:
arr = np.array([[1, 2, 3, 4],
                [0, 5, 0, 0],
                [2, 0, 1, 0]])

In [78]:
foo(arr, axis = 1)

array([4, 1, 2])

In [79]:
foo(arr, axis = 0)

array([2, 2, 2, 1])

In [80]:
arr1 = np.array([[[1, 2, 3, 4], [0, 5, 0, 0], [2, 0, 1, 0]],
                [[2, 0, 1, 0], [0, 5, 0, 0], [1, 2, 3, 4]]])

In [81]:
foo(arr1 , axis = 0)

array([[2, 1, 2, 1],
       [0, 2, 0, 0],
       [2, 1, 2, 1]])

In [82]:
foo(arr1 , axis = 1)

array([[2, 2, 2, 1],
       [2, 2, 2, 1]])

In [83]:
foo(arr1 , axis = 2)

array([[4, 1, 2],
       [2, 1, 4]])

### expalintion for above program : 

* Step-1 : creat a function which accepts array and axis .
arr ----> which is array , axis ----> in arrays we have axis ,when axis=0 it collapsing the rows ,axis=1 is for columns

* step-2 : if arr.ndim==2: ---> if the given array is 2 dim array then it executes the beneath of if statement .
* step-3 : x=np.where(arr != 0, 1, 0) "Where" Function to create a new array x with the same shape as the input array. The elements of x are 1((which is True) the corresponding elements of arr are not equal to 0 ,if it is equal to zero then it is 0(which is False ).
* step-4 : counts=np.sum(x,axis=axis)---> sum of x ,is nothing but count of non zero elements.
* step-5 : returns counts
* step-6 : the above functionality is same for 3 dim array

#### 3. 1. You are given a 2D NumPy array of data representing student scores. Each row represents a student, and each column represents a subject. Extract the scores of all students who scored above 90 in at least one subject. Provide the resulting array.

In [9]:
def foo_marks(scores):
    high = []
    for row in scores:
        for score in row:
            if score > 90:
                high.append(row)
                break
    return np.array(high)

In [10]:
marks = np.array([[85, 89, 88],  
                  [78, 89, 94],
                  [91, 87, 90],
                  [87, 95, 84]])


In [11]:
foo_marks(marks)

array([[78, 89, 94],
       [91, 87, 90],
       [87, 95, 84]])

### expalintion for above program : 

* step -1 : Define the function foo_marks that takes one parameter called scores. This will be the 2D array of test scores.

* step - 2: Initialize an empty list called high to store the rows of students who scored above 90.

* step - 3 : Start iterating through each row in the scores array using a for loop. So row will contain the test scores for each student.

* step - 4 : Nest another for loop that goes through each test score in the current row.We assign each test score to the variable score.

* step - 5 : Check if the current test score is greater than 90 using a conditional.

* step - 6 : If true, then we found a score above 90 for this student. So append the entire current row to the list high.

* step - 7 : Use break to stop going through anymore scores in this row since we already found a >90 score.

* step - 8 : After checking all rows in the array, convert the high list into a NumPy array.

* step - 9 : Return the high scoring rows array.

#### 3.2. You are provided with a 2D NumPy array of data representing sales data for different products. Each row corresponds to a product, and each column represents the monthly sales for a specific month. Calculate the following statistics for each product: mean, median, standard deviation, and the month with the highest sales.

In [23]:
data = np.array([[120, 150, 130, 110],
                [200, 180, 220, 250],
                [90, 100,95, 110],
                [300, 280, 320, 340]])

def get_mean(array):
    return np.mean(array)
def get_median(array):
    return np.median(array)  
def get_std(array):
    return np.std(array)   
def get_max_month(array):
    return np.argmax(array) + 1

In [24]:
def foo(row):
    mean = get_mean(row)
    median = get_median(row)
    stdev = get_std(row) 
    max_month = get_max_month(row)
    print(f"Mean: {mean:.2f}, Median: {median:.2f}, STD: {stdev:.2f}, Best Month: {max_month}")

In [25]:
for product_row in data:
    foo(product_row)

Mean: 127.50, Median: 125.00, STD: 14.79, Best Month: 2
Mean: 212.50, Median: 210.00, STD: 25.86, Best Month: 4
Mean: 98.75, Median: 97.50, STD: 7.40, Best Month: 4
Mean: 310.00, Median: 310.00, STD: 22.36, Best Month: 4


### expalintion for above program : 

1. <b>Define the statistics functions : </b>

* step - 1 : get_mean() => Calculates and returns the mean of the given array (Numpy vectorized)
* step - 2 : get_median() => Calculates and returns the median of the array
* step - 3 : get_std() => Calculates and returns the standard deviation value
* step - 4 : get_max_month() => Finds the index of the max value from array and returns the index +1 (Month number).
2. <b> Define the foo() method : </b> 

* step - 5 : Calls get_mean(), get_median(), get_std() and get_max_month() by passing the row as argument to calculate the statistics on it.
* step - 6 : It stores each returned statistic in a variable (mean, median, stdev, max_month)
* step - 7 : Prints the results using f-string formatting to 2 decimal places
3. <b>Loop over data : </b>
* step - 8 : We have our data array containing rows of product sales
* step - 9 : We loop over each product_row in data
* step - 10 : We pass that product_row into foo() to print statistics

#### 3.3.  Create a NumPy array of size 1000 with random integers between 1 and 100. Then, use NumPy functions to find the top 10 most frequently occurring values in the array.


In [26]:
arr = np.random.randint(1, 100, 1000)

In [27]:
arr

array([90, 48, 55, 74, 75, 87, 27, 85, 54, 55, 60, 99, 57, 55, 14, 28, 90,
       77, 79, 33, 74, 33, 75, 74, 23, 31, 42, 84, 31, 62, 15, 45, 80, 74,
       43, 85, 69, 97, 36, 28, 12,  4, 28, 33, 12, 36, 88, 83, 98, 51, 99,
       93, 24, 50, 36, 85, 64,  8, 67, 11, 46, 71, 99,  5, 16, 31, 60, 77,
       90, 20, 89, 38, 17, 43, 41, 86, 91, 97, 81, 64, 85, 96, 32, 93, 33,
        7, 35, 54, 59, 36, 75, 95, 57, 89, 66, 34, 69, 74, 16, 59,  7, 20,
       29, 49, 14, 48, 20, 42, 63, 26, 64,  9, 29, 85, 50, 47,  2, 65, 20,
       83, 56, 48, 90,  5, 72, 63, 79, 30, 47, 17, 56, 23, 84, 88, 89, 15,
       72, 29, 27, 16, 95, 53, 97, 87,  3, 29, 54, 89, 41, 40, 67,  5, 52,
       23, 59, 81, 83,  1, 77, 30, 95, 15, 67,  8, 60, 11, 15, 63, 54, 57,
       31, 14, 78, 94, 10, 83, 33, 44, 52, 77, 21,  3,  1, 33, 40, 45, 71,
       11, 74, 85, 76, 54, 31,  7, 38, 77, 45, 50, 53, 32, 78, 80, 13, 61,
       69, 14, 32, 33, 59, 71, 67, 31, 90, 51, 92, 68, 86, 66, 51, 23,  5,
       73, 35,  9, 95, 83

In [28]:
unique, counts = np.unique(arr, return_counts=True)

In [29]:
freq = unique[np.argsort(counts)[::-1][:10]  

In [31]:
print("top 10 most frequent values that are occuring : ")
for index in freq:
    print(f'value : {index}, counts : {counts[index]}')

top 10 most frequent values that are occuring : 
value : 43, counts : 8
value : 83, counts : 9
value : 54, counts : 12
value : 64, counts : 9
value : 91, counts : 11
value : 90, counts : 14
value : 31, counts : 9
value : 63, counts : 14
value : 85, counts : 12
value : 72, counts : 6


### expalintion for above program : 

* step - 1 : Generate a random array arr with 1000 integers between 1 and 100 using np.random.randint.
* step - 2 : Get the unique values present and their counts by passing return_counts=True in np.unique() function. This returns two arrays - unique values and their counts.
* step - 3 : Sort the count array in descending order with np.argsort()[::-1]. Slicing [:10] limits to top 10 indices.
* step - 4 : Use the sorted indices to index into the unique values array, so freq now contains the top 10 most frequent values.
* step - 5 : Print heading for output results
* step - 6 : Iterate through each of the top 10 values in freq array using a for loop
* step - 7 : Print the value and fetch its corresponding count from the counts array using index position.